spring:
  datasource:
    url:
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:
  druid:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'